import turtle
wn=turtle.Screen()
square=turtle.Turtle()
square.shape("turtle")
square.color(input("enter your color for L1: "))
square.forward(float(input("enter your size for L1: ")))
square.rt(90)
square.color(input("enter your color for L2: "))
square.forward(float(input("enter your size for L2: ")))
square.rt(90)
square.color(input("enter your color for L3: "))
square.forward(float(input("enter your size for L3: ")))
square.rt(90)
square.color(input("enter your color for L4: "))
square.forward(float(input("enter your size for L4: ")))
wn.mainloop()